//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Triamec.Tam.Samples.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// The number of values to import per axis and line. A value of 1 indicates positions, 2 positions and velocities, and 3 positions, velocities and accelerations.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(Triamec.Configuration.WorkspaceSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("The number of values to import per axis and line. A value of 1 indicates position" +
            "s, 2 positions and velocities, and 3 positions, velocities and accelerations.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int PositionDimensionality {
            get {
                return ((int)(this["PositionDimensionality"]));
            }
            set {
                this["PositionDimensionality"] = value;
            }
        }
    }
}
